CREATE TABLE INVENTORY (
Car_Stock_Num INT AUTO_INCREMENT,
Car_Make VARCHAR(50),
Car_Model VARCHAR(50),
Car_Year INT, var car_stock_num = car[0]
Car_Price INT,
Car_Mileage INT,
Car_BodyType VARCHAR(50),
Car_Condition VARCHAR(50),
Car_Color VARCHAR(50),
PRIMARY KEY (Car_Stock_Num)
);

CREATE TABLE EMPLOYEE (
Emp_ID INT AUTO_INCREMENT,
Emp_Username VARCHAR(50),
Emp_PasswordHash VARCHAR(50) NOT NULL,
Emp_FirstName VARCHAR(50),
Emp_LastName VARCHAR(50),
Emp_Role VARCHAR(50),
PRIMARY KEY (Emp_ID, Emp_Username)
);

CREATE TABLE PHONE (
Emp_ID INT,
Emp_Phone VARCHAR(50),
FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(Emp_ID)
);

CREATE TABLE EMAIL (
Emp_ID INT,
Emp_Email VARCHAR(50),
FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(Emp_ID)
);

CREATE TABLE REVIEW(
REVIEW_ID INT AUTO_INCREMENT,
REVIEW_COMMENT TEXT(5000),
REVIEW_RATING INT,
PRIMARY KEY (Review_ID)
);

CREATE TABLE IMAGES (
Car_Stock_Num INT,
Car_Image VARCHAR(160),
FOREIGN KEY (Car_Stock_Num) REFERENCES INVENTORY(Car_Stock_Num)
);

/* Meets 2NF criteria