CREATE TABLE INVENTORY (
Car_Stock_Num INT AUTO_INCREMENT,
Car_Make VARCHAR(50),
Car_Model VARCHAR(50),
Car_Year INT,
Car_Price INT,
Car_Mileage INT,
Car_BodyType VARCHAR(50),
Car_Condition VARCHAR(50),
Car_Color VARCHAR(50),
PRIMARY KEY (Car_Stock_Num)
);

CREATE TABLE EMPLOYEE (
Emp_ID INT AUTO_INCREMENT,
Emp_Username VARCHAR(50),
Emp_PasswordHash VARCHAR(100) NOT NULL,
Emp_FirstName VARCHAR(50),
Emp_LastName VARCHAR(50),
Emp_Role VARCHAR(50),
PRIMARY KEY (Emp_ID, Emp_Username)
);

CREATE TABLE PHONE (
Emp_ID INT,
Emp_Phone VARCHAR(50),
FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(Emp_ID)
);

CREATE TABLE EMAIL (
Emp_ID INT,
Emp_Email VARCHAR(50),
FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(Emp_ID)
);

/* Meets 2NF criteria